import { Slider, GroupBox, HorizontalBox, VerticalBox, LineEdit, Button } from "std-widgets.slint";

export component MainWindow inherits Window {
    in-out property <float> pitch: 0.15;
    in-out property <float> yaw: 0.5;
    out property <int> chart_width;
    out property <int> chart_height;
    property <length> mainHeight;

    pure callback render_plot(int, int) -> image;

    title: "Gráfica Poblacional";
    preferred-width: 800px;
    preferred-height: 600px;

    HorizontalBox {
        VerticalBox {
            LineEdit {
                placeholder-text: "Ingresa la tasa de crecimiento poblacional";
            }

            LineEdit {
                placeholder-text: "Ingresa el valor inicial de la población";
            }

            LineEdit {
                placeholder-text: "Ingresa el tiempo";
            }

            Button {
                text: "Renderizar";
                clicked => {
                    root.render_plot(chart-image.width / 1px, chart-image.height / 1px);
                }
            }
        }

        VerticalBox {
            chart_image := Image {
                source: root.render_plot(800, 1000);
                touch := TouchArea {
                    property <float> pressed-pitch;
                    property <float> pressed-yaw;

                    pointer-event(event) => {
                        if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                            self.pressed-pitch = root.pitch;
                            self.pressed-yaw = root.yaw;
                        }
                    }
                    moved => {
                        if (self.enabled && self.pressed) {
                            root.pitch = self.pressed-pitch + (touch.mouse-y - touch.pressed-y) / self.height * 3.14;
                            root.yaw = self.pressed-yaw - (touch.mouse-x - touch.pressed-x) / self.width * 3.14;
                        }
                    }
                    mouse-cursor: self.pressed ? MouseCursor.grabbing : MouseCursor.grab;
                }
            }
        }
    }
}
